### ISSUE TITLE
How to configure for using other specificy gcc by Buildroot 

### ISSUE THREAD

**Issue by dr-begemot** [protobuf-c/protobuf-c-rpc#15]
Hi, I want to compile protobuf-c-rpc for the embedded system using bulldroot, could you tell me how this can be done?

Usually it's enough just to specify `arm-buildroot-linux-gnueabihf-gcc` instead of `gcc` in Makefile; 
and need to change output directories in `make install` from
`/usr/local/include/` and `/usr/local/lib/` to
`.../buildroot/output/target/usr/include` and `.../buildroot/output/target/usr/lib` for example:

How do I change the instruction set to achieve this?

**Comment by lipnitsk** [comment]
Autotools should allow for this. I would suggest to look at projects such as OpenWrt do this. If there is a protobuf-c-rpc specific issue feel free to open a new issue
