### ISSUE TITLE
Is there a different between c-rpc and gRPC?

### ISSUE THREAD

**Issue by pauldotknopf** [protobuf-c/protobuf-c-rpc#21]
Should I be able to invoke gRPC/C++ servers with this c-rpc API?

If so, I'm getting errors, but I want to make sure this is supported before I file a proper issue.

**Comment by surfingtomchen** [comment]
I guess the client must communicate with the server with c-rpc on it?

**Comment by lipnitsk** [comment]
If you reverse engineer or find documentation for the underlying RPC protocol and write your own serialize/deserialize routines it may be possible, but definitely something that is not supported out of box.
