### ISSUE TITLE
Compatibility with protobuf.socketrpc

### ISSUE THREAD

**Issue by gabb99** [protobuf-c/protobuf-c-rpc#4]
protobuf.socketrpc uses a slightly more complex rpc wrapper (along with a .proto definition), which is incompatible with protobuf-c-rpc's fixed size header/response.

Using this, protobuf-c-rpc could be scriptable in Java/Python as an example.

**Comment by lipnitsk** [comment]
@gabb99,
I'm going to close this issue. Feel free to add this code to the examples directory as a Pull Request or a wiki entry.
